# Generated by Django 4.1.7 on 2023-04-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
