# Generated by Django 4.1.7 on 2023-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0002_books_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('NF', 'Non-Fiction'), ('FI', 'Fiction')], max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='bookshop_app.categories'),
        ),
    ]
