# Generated by Django 4.1.7 on 2023-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0003_alter_authors_about_alter_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(choices=[('PB', 'Paperback'), ('HB', 'Hardback'), ('LT', 'Leather')], default='PB', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
