# Generated by Django 4.1.7 on 2023-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0004_books_number_of_pages_books_publisher_books_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
