# Generated by Django 4.1.7 on 2023-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0005_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
