# Generated by Django 4.1.7 on 2023-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0006_alter_books_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
