# Generated by Django 4.1.7 on 2023-05-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0007_alter_books_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(upload_to='static/images/Covers/'),
        ),
    ]
