# Generated by Django 4.1.7 on 2023-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0009_alter_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
